### ISSUE TITLE
Please make SSL configuration available through Environment Variables

### ISSUE THREAD

**Issue by grummelf** [phpipam-docker/phpipam-docker#15]
Hi, I guess this is an easy one.
Can you please enable the config.docker.php file to configure SSL settings for database connection by using environment variables such as:

```
$db['ssl'] = file_env('IPAM_DATABASE_SSL', $db['ssl']);
$db['ssl_cipher'] = file_env('IPAM_DATABASE_SSL_CIPHER', $db['ssl_cipher']);
[...]
```

We really enjoy using IPAM, thank you for that great product. :)

**Comment by GaryAllan** [comment]
I've added `IPAM_CONFIG_FILE` to 1.5/master/nightly allowing you to specify an alternative config.php file.
e.g. Mount a new volume at /config containing /config/config.ssl.php

I may add the IPAM_DATABASE_SSL.... at a later date

Closed via https://github.com/phpipam/phpipam/commit/0ba2fd95b1f4e20e8d5f8b404a03ae3a7876b441
