### ISSUE TITLE
PB import DB

### ISSUE THREAD

**Issue by barto95100** [phpipam-docker/phpipam-docker#16]
Hi,

the export dump sql MIGRATE.sql its necessarry on folder DB

but thos folder is necessary on  /var/lib/mysql/db/MIGRATE.sql or other location 

Because when I test to put the file in the /var/lib/mysql/db/  i received this error:

Cannot access file db/MIGRATE.sql!

**Comment by GaryAllan** [comment]
The folder would be /phpipam/db/
