### ISSUE TITLE
Timezone on server off

### ISSUE THREAD

**Issue by gawainXX** [phpipam-docker/phpipam-docker#18]
I've set the TimeZone environment property but it seems to be failing back to UTC as all of my ping and discovery timestamps are 8 hours forward.

snippet from my docker compose

phpipam-web:
    image: phpipam/phpipam-www:latest
    # ports:
      # - "80:80"
    environment:
      - TZ=America/Los_Angeles   
      - IPAM_DATABASE_HOST=phpipam-mariadb
      - IPAM_DATABASE_PASS=${PHPIPAM_PASS}
      - IPAM_DATABASE_WEBHOST=%

  phpipam-cron:
    image: phpipam/phpipam-cron:latest
    environment:
      - TZ=America/Los_Angeles

**Comment by GaryAllan** [comment]
Hi

Do your containers have Internet access?

I've been looking at the Alpine setup-timezone scripts and they call "apk add tzdata"

**Comment by gawainXX** [comment]
Only www does

**Comment by GaryAllan** [comment]
Thanks, I'll do some testing and confirm if that's the issue.

**Comment by gawainXX** [comment]
Ok, thanks.
Right now it's defaulting to GMT so all timestamps in the webui are off by
that amount.

**Comment by GaryAllan** [comment]
Just to eliminate the obvious....can you confirm you're using a forward slash in your docker environment for TZ?

TZ=America/Los_Angeles and not TZ= America\Los_Angeles


ENV from the command line in the container will show all values

**Comment by gawainXX** [comment]
environment:
      - TZ=America/Los_Angeles
      - IPAM_DATABASE_HOST=phpipam-mariadb
      - IPAM_DATABASE_PASS=${PHPIPAM_PASS}
      - IPAM_DATABASE_WEBHOST=%

**Comment by gawainXX** [comment]
The timestamps appear to have corrected themselves. *Shrug*
Hosts check enabled Last scan 2022-03-07 17:10:00
Discover new hosts enabled Last scan 2022-03-07 17:10:00

**Comment by gawainXX** [comment]
issue appears to have fixed itself
