### ISSUE TITLE
Trouble getting working with ssl reverse proxy apache on the hostmachine.  jQuery error!

### ISSUE THREAD

**Issue by ntaken** [phpipam-docker/phpipam-docker#2]
Hello!

Used the docker-compose.yml standalone docker.

Changed ports to 

    "4466:80"

and added in environment:

 - IPAM_BASE=/phpipam/

As I want to access phpipam on https://server.com/phpipam/

From the Virtualhost Apache:
 
    ProxyRequests Off
    SSLProxyEngine on
    ProxyPreserveHost on

    RequestHeader set X-Forwarded-Proto "https"
    ProxyPass /phpipam/ http://127.0.0.1:4466/phpipam/
    ProxyPassReverse /phpipam/ http://127.0.0.1:4466/phpipam/

My web browser complains about:

4index.php?page=install:1 Refused to apply style from 'https://server.com/phpipam/index.php?page=install' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

3index.php?page=install:1 Refused to execute script from 'https://server.com/phpipam/index.php?page=install' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

index.php?page=install:36 Uncaught ReferenceError: $ is not defined
    at index.php?page=install:36
(anonymous) @ index.php?page=install:36

index.php?page=install:25 Resource interpreted as Stylesheet but transferred with MIME type text/html: "https://server.com/phpipam/css/bootstrap/bootstrap.min.css?v=1.4.2_r027_v25".
index.php?page=install:26 Resource interpreted as Stylesheet but transferred with MIME type text/html: "https://server.com/phpipam/css/bootstrap/bootstrap-custom.css?v=1.4.2_r027_v25".
index.php?page=install:27 Resource interpreted as Stylesheet but transferred with MIME type text/html: "https://server.com/phpipam/css/font-awesome/font-awesome.min.css?v=1.4.2_r027_v25".
index.php?page=install:28 Resource interpreted as Stylesheet but transferred with MIME type text/html: "https://server.com/phpipam/css/bootstrap/bootstrap-custom-dark.css?v=1.4.2_r027_v25".

**Comment by ntaken** [comment]
Fixed my problem by changing the documentroot in apache.conf to /. On the web container.

**Comment by kjanss** [comment]
Hi, actually, running phpipam from a subpath should be possible and is what I have been doing for 5 years now.
I just moved my site to a new webserver and started seeing this issue. (so the previous site was running fine, also from a docker image).
I confirm after changing the site url on the backend container to '/', it starts to work.
when moving it back to '/phpipam/', it stops working. (I am also changing IPAM_BASE).
I suspect the apache configuration. Can this issue be re-opened ?

**Comment by GaryAllan** [comment]
Please feeback following Fix for reverse proxies js/css issue #8
