### ISSUE TITLE
Pls add "php_mcrypt" to allow SAML2

### ISSUE THREAD

**Issue by joaocc** [phpipam-docker/phpipam-docker#20]
Hi. Running on a container environment, adding SAML2 returns the following error message "php mcrypt extension missing!". Thanks

**Comment by joaocc** [comment]
Just found out that libmcrypt stopped being supported in alpine 3.12.

**Comment by GaryAllan** [comment]
The 1.5 & nightly images don't need mcrypt.

duplicate of #6
