### ISSUE TITLE
wrong version with a tag 'latest'

### ISSUE THREAD

**Issue by almorr** [phpipam-docker/phpipam-docker#22]
With a tag :latest from docker hub i've got a docker image with a version 1.5:
[phpIPAM IP address management [v1.5.0]](http://phpipam.net/) git [f8c651de](https://github.com/phpipam/phpipam/tree/f8c651de)

**Comment by GaryAllan** [comment]
Hello,

1.5.0 is the latest release.

If you specifically want the 1.4 version there is a 1.4x tag that tracks the phpIPAM 1.4 git tree and is also updated with Alpine Linux security fixes.

Or pick a static tag (v1.4.7 et al) which are snapshots never updated (Alpine or phpIPAM)

**Comment by GaryAllan** [comment]
https://github.com/phpipam/phpipam/releases

Thanks, I'll update the dockerhub site when I get the chance.
