### ISSUE TITLE
Autodiscovering unused IPs

### ISSUE THREAD

**Issue by theniwo** [phpipam-docker/phpipam-docker#4]
phpipam finds all sorts of new hosts, that doesn't exist.

**Comment by GaryAllan** [comment]
Hi,

Are you using fping? Try switching to ping.

Someone recently posted to a fping GitHub bug report. Fping gets confused with the ping responses if multiple fpings processes are run concurrently  (phpIPAM does this).

I'll see if I can dig out the link.

**Comment by GaryAllan** [comment]
Found it...

https://github.com/phpipam/phpipam/issues/2888#issuecomment-767097411

**Comment by GaryAllan** [comment]
> As an added information: I cannot reproduce this issue on Debian Stable. The difference is that fping is v4.2 instead of v5.0 when I encountered this bug.
> An issue is currently opened for fping since version 4.3 (https://github.com/schweikert/fping/issues/183). Basically, parallels fping requests would say some IPs are alive although they are really not.

**Comment by theniwo** [comment]
Thanx
I run phpipam in docker with the latest release.
Version of fping is indeed
```
/ # which fping
/usr/sbin/fping
/ # fping --version
fping: Version 4.2
```
but ping is selected under the ICMP settings. There is also the choice of pear ping, which I will try out next. The other thing I noticed is, that the path to fping was wrong (`/bin/fping`)

**Comment by theniwo** [comment]
I corrected the path to `/usr/sbin/fping` and selected fping. No false positives until now.
