### ISSUE TITLE
error after update to 1.6

### ISSUE THREAD

**Issue by dormancygrace** [phpipam-docker/phpipam-docker#41]
I'm getting this after pulling new images 
![image](https://github.com/phpipam-docker/phpipam-docker/assets/20384748/69e60821-efd9-46ad-83e9-8a7423413f95)

**Comment by GaryAllan** [comment]
If you're behind a proxy/load balancer look at the new IPAM_TRUST_X_FORWARDED env

**Comment by dormancygrace** [comment]
@GaryAllan Thank you!
