### ISSUE TITLE
Upgrade from 1.5.2 to 1.6.0

### ISSUE THREAD

**Issue by siwyroot** [phpipam-docker/phpipam-docker#42]
Hello, I was trying to update my deployment on OpenShift from 1.5.2 to 1.6.0, application started but I could not login anymore to it. Login screen is not fully loaded and I can see `jQuery error!` error on top.

![image](https://github.com/phpipam-docker/phpipam-docker/assets/30121965/2a952c8e-9963-47bb-b11d-857d1e76aa05)

I could not find anything in logs, is there a special update procedure? I had to revert back to 1.5.2.

**Comment by GaryAllan** [comment]
There are notes in the CHANGELOG

Anyone behind a reverseproxy/lb needs to look at IPAM_TRUST_X_FORWARDED env or config.php $trust_x_forwarded_headers

**Comment by siwyroot** [comment]
D'oh! Tanks for help, after setting this to true I could login and was asked to update database. Closing
