### ISSUE TITLE
Docker image with radius fix

### ISSUE THREAD

**Issue by jonare77** [phpipam-docker/phpipam-docker#43]
Does your latest image include a fix for the radius problem ? Thanks for you work !

**Comment by GaryAllan** [comment]
Hi,

The nightly tag tracks the master branch containing the updated radius library. 

Cron job runs daily and rebuilds if there are alpine security fixes or changes to git tree.

**Comment by jonare77** [comment]
thank you

**Comment by jonare77** [comment]
thank you

**Comment by GaryAllan** [comment]
Hello,
The builds should now also include the composer modules.

Please re-open an issue if there is a problem.

**Comment by jonare77** [comment]
Still getting error when using radius. Not working, will post this in phpipam git repo.

`PHP Fatal error:  Uncaught ValueError: socket_connect(): Argument #3 ($port) cannot be null when the socket type is AF_INET in /phpipam/functions/classes/class.Radius.php:742\nStack trace:\n#0 /phpipam/functions/classes/class.Radius.php(742): socket_connect()\n#1 /phpipam/functions/classes/class.User.php(1185): Radius->AccessRequest()\n#2 /phpipam/functions/classes/class.User.php(837): User->auth_radius()\n#3 /phpipam/app/login/login_check.php(51): User->authenticate()\n#4 {main}\n  thrown in /phpipam/functions/classes/class.Radius.php on line 742,`

**Comment by GaryAllan** [comment]
Hi

I've just had a quick look. I thought Miha had pulled in a newer radius library but there are still references to the old one.

I'll take a look but I'll have to build a radius server to test, maybe in a few weekends.
