### ISSUE TITLE
jQuery Error

### ISSUE THREAD

**Issue by chr1sn3al** [phpipam-docker/phpipam-docker#44]
Appears that the phpIpam has moved to version 1.7.

As I'm using the tag :latest    it appears that it is now phpipam-web is erroring with jQuery Error.. (Appears in 1.7 they updated the jQuery to a newer version.

Still investigating issue...  But if you have any insights..

**Comment by chr1sn3al** [comment]
I switched from :latest to :1.6x TAG.. Still have same error...   Appears 
Similar to https://github.com/phpipam/phpipam/issues/2478

**Comment by GaryAllan** [comment]
Hi,

:latest should be v1.6.x.  Try the v1.6.0 tag

**Comment by chr1sn3al** [comment]
Updated TAG.. I appears it's pulling phpipam/phpipam-www:1.6.0
<img width="1421" alt="image" src="https://github.com/phpipam-docker/phpipam-docker/assets/20053509/adc2c475-ea60-40a3-8c2a-607eea6a556a">

**Comment by chr1sn3al** [comment]
tag:latest is pulling 1.6.0   But still have jQuery error.. (Working system until last night...)  So Not sure where to go from here

**Comment by chr1sn3al** [comment]
Finally found it....  had to add two environment variables...  to the kompose...     Because we use an nginx ingress controller...  needed the IPAM_TRUST_X_FORWARDED   and I also added the IPAM_BASE

IPAM_BASE="/"
IPAM_TRUST_X_FORWARDED=true

**Comment by jilabaca** [comment]
@chr1sn3al thanks!!
