### ISSUE TITLE
Crashing frontend when updating from 1.5x to 1.6x

### ISSUE THREAD

**Issue by ne0x86** [phpipam-docker/phpipam-docker#47]
Hi there, Im using 1.5x without any issues.

I decied to update to 1.6x because there is some php vulnerabilities and when update, frontend fails with jQuery Error in home page. Also I cannot login:

![image](https://github.com/phpipam-docker/phpipam-docker/assets/24698438/9fe64093-006e-460e-8c6a-3c2d1e60c5d7)

Rolling back to 1.5x works fine.

Any idea?

**Comment by GaryAllan** [comment]
See `IPAM_TRUST_X_FORWARDED` 

* Enabling IPAM_TRUST_X_FORWARDED without filtering request from end-clients can result in security issues. Ensure the headers are filtered or overwritten by the reverse-proxy/loadbalancer and can not be set by the clients.

Also mentioned in the CHANGELOG

**Comment by ne0x86** [comment]
Ops sorry. I didnt saw this. Now its working.

So much appreciated.
