### ISSUE TITLE
Issues with phpipam-www upgrade from 1.5.3

### ISSUE THREAD

**Issue by trahman-hm** [phpipam-docker/phpipam-docker#49]
Hello,

I'm trying to upgrade a running phpipam instance running on Ubuntu/Docker.  The working version is 1.5.3 but when I tried to upgrade to 1.6x, I can't get the system to come up.  The phpipam-www container keeps restarting and my compose logs seem to be filling up with repeats of the following entries:

phpipam-web      | Info: Setting timezone to America/New_York
phpipam-web      | AH00526: Syntax error on line 1 of -c/-C directives:
phpipam-web      | Alias takes 1-2 arguments, a fakename and a realname, or a realname in a Location

The system is set up with an HAProxy front-end and a mysql backend as well as a syslogd instance for logging.

Here is a redacted copy of my docker-compose.yml file:

-----
services:

  mysql:
    image: mysql:8.0
    container_name: mysql-phpipam
    restart: unless-stopped
    volumes:
      - "/opt/mysql-data:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=<HIDDEN>
      - MYSQL_DATABASE=<HIDDEN>
      - MYSQL_USER=<HIDDEN>
      - MYSQL_PASSWORD=<HIDDEN>
    networks:
      - net-phpipam

  syslog:
    image: balabit/syslog-ng
    container_name: syslog-ng
    restart: unless-stopped
    volumes:
      - "/opt/syslog-ng/etc/syslog-ng.conf:/etc/syslog-ng/syslog-ng.conf"
      - "/opt/syslog-ng/logs:/var/log"
    networks:
      - net-phpipam

  phpipam-web:
    image: phpipam/phpipam-www:1.6x
    container_name: phpipam-web
    restart: unless-stopped
    depends_on:
      - mysql
    environment:
      - TZ=America/New_York
      - IPAM_DATABASE_HOST=mysql-phpipam
      - IPAM_DATABASE_NAME=<HIDDEN>
      - IPAM_DATABASE_USER=<HIDDEN>
      - IPAM_DATABASE_PASS=<HIDDEN>
      - IPAM_DATABASE_WEBHOST=%
      - IPAM_BASE="/"
      - IPAM_TRUST_X_FORWARDED="true"
    networks:
      - net-phpipam

  phpipam-cron:
    image: phpipam/phpipam-cron:1.6x
    container_name: phpipam-cron
    restart: unless-stopped
    depends_on:
      - phpipam-web
    environment:
      - TZ=America/New_York
      - IPAM_DATABASE_HOST=mysql-phpipam
      - IPAM_DATABASE_NAME=<HIDDEN>
      - IPAM_DATABASE_USER=<HIDDEN>
      - IPAM_DATABASE_PASS=<HIDDEN>
      - SCAN_INTERVAL=1h
    networks:
      - net-phpipam

  haproxy:
    image: haproxy:2.9
    container_name: haproxy-phpipam
    restart: unless-stopped
    depends_on:
      - phpipam-web
    ports:
      - "80:80"
      - "443:443"
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0
    volumes:
      - "/opt/haproxy-etc:/usr/local/etc/haproxy:ro"
      - "/opt/haproxy-certs:/etc/ssl/certs:ro"
    networks:
      - net-phpipam

networks:
  net-phpipam:
    name: net-phpipam
    driver: bridge

-----

Any thoughts as to what the mentioned repetitive log errors are and possibly how to fix the solution to get the upgrade completed?

Thanks

**Comment by trahman-hm** [comment]
One additional comment, the following lines were not present in my original 1.5.3 docker-compose.yml file and were added to try and fix things in the phpipam-www config stanza:

- IPAM_DATABASE_WEBHOST=%
- IPAM_BASE="/"
- IPAM_TRUST_X_FORWARDED="true"

Thanks

**Comment by GaryAllan** [comment]
Try removing  the quotes from `- IPAM_BASE="/"`   

Or just remove this env completely (the default is /)

**Comment by trahman-hm** [comment]
Thanks - that led me on a path to resolution.  My phpipam instance is now upgraded to 1.6x and is running fine.
