### ISSUE TITLE
Unable to use API

### ISSUE THREAD

**Issue by sidhoah8** [phpipam-docker/phpipam-docker#5]
Maybe I'm missing something but it doesn't seem to be possible to use the API with the docker image as it stands.
- API requires SSL by default
- Docker image only works over HTTP with the expectation of using a reverse proxy for the SSL
- Attempt to set "App security" to "User token" (no SSL) and we need to update $api_allow_unsafe in config.php... which we can't access and there is no external variable.

Perhaps an external variable could be added to configure $api_allow_unsafe?

**Comment by GaryAllan** [comment]
Hi,
The API should be functional behind a reverse SSL proxy. It should detect that the proxy is offloading the SSL.

**Comment by sidhoah8** [comment]
Ok, great. I assumed it was a missing feature.  I'll try that and if there's a problem, I'll open a new issue.
