### ISSUE TITLE
Warning to disable installation scripts

### ISSUE THREAD

**Issue by ahrenstein** [phpipam-docker/phpipam-docker#50]
When running the container after installation as of 1.7 the following appears on the login screen

```
Please disable installaion scripts in config.php
$disable_installer=true;
```

I'm running this in Kubernetes and would prefer not to manually map a config.php file. Would it be possible to disable this as an env var or flag of some kind?

**Comment by GaryAllan** [comment]
Hi

Env (book) is 'IPAM_DISABLE_INSTALLER'.

**Comment by GaryAllan** [comment]
Hi,

It came in as a last minute security fix. Thanks for reminding me, I'll update the docs.

**Comment by ahrenstein** [comment]
No problem!
