### ISSUE TITLE
missing php mcrypt in phpipam-www docker image

### ISSUE THREAD

**Issue by bigTuxer** [phpipam-docker/phpipam-docker#6]
Hi,

i have deployed an instance of your phpipam-www dockerimage on my kubernetes cluster.  
Everything went well and phpipam is up and running. 

Now i want to configure SAML2 for my Keycloak, but i get the message that php mcrypt is missing:  
![image](https://user-images.githubusercontent.com/44808033/108691548-eb67e500-74fb-11eb-8429-87f9c3b3b038.png)
  
I had a look in the dockerfile for your phpipam-base dockerimage, there you install a bunch of packages but php mcrypt is missing. i'm not so deep into alpine, i'm not sure if mcrypt is a default dependency of the php package.  

Is there a possibility to add php mcrypt to the base image?  

I've deployed the following image: phpipam/phpipam-www:1.4x

**Comment by GaryAllan** [comment]
Nope, mcrypt is been deprecated for a few years and is not available in Alpine (or any modern OS)

The SAML module in 1.5/nightly has been updated and does not require mcrypt.

**Comment by bigTuxer** [comment]
@GaryAllan Thanks a lot for your fast answer :-)  

In that case 1.4 is a dead end for me and i've to move directly to 1.5

**Comment by GaryAllan** [comment]
The 1.5 docker image is a preview/RC.

Hopefully 1.5.0 will be officially released soon.
