### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by cacack** [phpipam-docker/phpipam-docker#7]
Maybe I'm missing something, but using a very similar docker-compose file, I'm not able to get it working.  Given the use of the vanilla mariadb image, I suspect the problem is there isn't any SQL schema preloaded into the database container.

Is the expectation to walkthrough the installation wizard?

**Comment by cacack** [comment]
I was able to get beyond the initial wizard by adding the following environment variables to the database container:
```
MYSQL_DATABASE: "phpipam"
MYSQL_USER: "phpipam"
MYSQL_PASSWORD: "${PHPIPAM_DB_USER_PASSWORD}"
```

Then I could select the automatic install option.  But this still required choosing the advanced options and deselecting all of the choices.

**Comment by GaryAllan** [comment]
Hello,
The phpIPAM application will launch the installation wizard on first run.
