### ISSUE TITLE
Question: How should cron work

### ISSUE THREAD

**Issue by florianmulatz** [phpipam-docker/phpipam-docker#9]
Hi Guys,

I don't get it to be honest. How should the cron component work? Before I had a full LEMP stack where I simply put those two commands to cron:

```
*/15 * * * * /usr/bin/php /phpipam/functions/scripts/pingCheck.php
*/15 * * * * /usr/bin/php /phpipam/functions/scripts/discoveryCheck.php
```

but this seems not to work in this installation. When I do a manual update-scan in the web-if it works as expected.
When I execute these on docker-console it works on the web-container but not on the cron-container. 

How is the way it should work in this stack.

Thx in advance!

**Comment by GaryAllan** [comment]
The phpipam-www image contains just the webserver. You can run multiple instances of this on your docker/K8 cluster and load balance requests across them. To avoid duplicate scanning this image does not run cron jobs.

The phpipam-cron container runs the scheduled discovery tasks via the SCAN_INTERVAL environment variable. There should be be ONE running instance of this container on your cluster to avoid duplicate scanning/discovery of networks.

See the documentation on DockerHub.

Under the hood the images share the same code which is why the cron and discovery files are present in phpipam-www but are not activated.

**Comment by florianmulatz** [comment]
Hi GaryAllan,

Unfortunately - I don't get it. Is there anything to configure then in the cron-container?
I let anything default - so that means that it should be scanned automatically every hour. But it does not ?!

Is there anything to check or how to debug this behaviour?

Cheers

**Comment by GaryAllan** [comment]
Are you running on Docker or Kubernates?

**Comment by florianmulatz** [comment]
Running on docker ...

**Comment by GaryAllan** [comment]
When running under Docker, NET_ADMIN and NET_RAW container capabilities are required for ping and SNMP functionality.

Is there anything in the crib container logs?

**Comment by florianmulatz** [comment]
capabilities are set on both containers - nothing special in the logs from my point of perspective ...

from where are the commands run? - as I know it when there is a run-parts entry in crontab there should also be a corresponding shell script in the right folder?

```
phpipam # crontab -l
# do daily/weekly/monthly maintenance
# min   hour    day     month   weekday command
*/15    *       *       *       *       run-parts /etc/periodic/15min
0       *       *       *       *       run-parts /etc/periodic/hourly
0       2       *       *       *       run-parts /etc/periodic/daily
0       3       *       *       6       run-parts /etc/periodic/weekly
0       5       1       *       *       run-parts /etc/periodic/monthly

/phpipam # cd /etc/periodic/hourly/
/etc/periodic/hourly # ls -lhatr
total 8K     
drwxr-xr-x    7 root     root        4.0K Apr 14 11:24 ..
drwxr-xr-x    2 root     root        4.0K Apr 14 11:24 .
```
maybe my understanding is incorrect.

**Comment by GaryAllan** [comment]
/etc/crontabs/apache

**Comment by florianmulatz** [comment]
ok see it - should be executed then every 0 minute. But it looks like that it does not (or the data get's not populated to the mysql-db) - all my entries are "red" in phpipam

**Comment by GaryAllan** [comment]
Executed when minute=0,  so once per hour at each hour.
What's your timezone (TZ env)?

**Comment by florianmulatz** [comment]
```
TZ=Europe/London
```
I have no doubt that the cron is executed - but from my perspective it looks like that it's not populated to mysql-db. My entries stay red also when I execute the command manually on console (from cron-container). 

It WORKS when I execute the command from www-container.

**Comment by GaryAllan** [comment]
Check your routing/firewall rules. The two images are identical except for service startup scripts.

Can you ping the IPs from the cron container command line?

**Comment by florianmulatz** [comment]
There is no firewall in between.  This stack has been deployed via docker-compose (as of your documentation on docker-hub). It has created a network "phpipam_default" - all of the containers are part of it. I can ping each container from cron and vice-versa (can not test it on mysql one because ping-binary is not installed)

**Comment by GaryAllan** [comment]
Can you ping IPs in the subnets you're trying to scan from the cron container command line?

**Comment by florianmulatz** [comment]
yes
